// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelActiveCommand() {
  return window['go']['main']['App']['CancelActiveCommand']();
}

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function ConcatFiles(arg1, arg2) {
  return window['go']['main']['App']['ConcatFiles'](arg1, arg2);
}

export function ExtractStream(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExtractStream'](arg1, arg2, arg3, arg4, arg5);
}

export function GetMediaInfo(arg1) {
  return window['go']['main']['App']['GetMediaInfo'](arg1);
}

export function GetOutputSettings() {
  return window['go']['main']['App']['GetOutputSettings']();
}

export function GetVideoThumbnail(arg1) {
  return window['go']['main']['App']['GetVideoThumbnail'](arg1);
}

export function InjectStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['InjectStream'](arg1, arg2, arg3);
}

export function InstallFFmpegWindows() {
  return window['go']['main']['App']['InstallFFmpegWindows']();
}

export function RemuxFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemuxFile'](arg1, arg2, arg3);
}

export function RunCustomCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCustomCommand'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SetOutputSettings(arg1, arg2) {
  return window['go']['main']['App']['SetOutputSettings'](arg1, arg2);
}

export function TranscodeFile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18) {
  return window['go']['main']['App']['TranscodeFile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18);
}
