// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelActiveCommand():Promise<void>;

export function CheckFFmpeg():Promise<string>;

export function ConcatFiles(arg1:Array<string>,arg2:number):Promise<string>;

export function ExtractStream(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number):Promise<string>;

export function GetMediaInfo(arg1:string):Promise<string>;

export function GetOutputSettings():Promise<Record<string, string>>;

export function GetVideoThumbnail(arg1:string):Promise<string>;

export function InjectStream(arg1:string,arg2:string,arg3:number):Promise<string>;

export function InstallFFmpegWindows():Promise<void>;

export function RemuxFile(arg1:string,arg2:string,arg3:number):Promise<string>;

export function RunCustomCommand(arg1:string,arg2:number):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetOutputSettings(arg1:string,arg2:string):Promise<void>;

export function TranscodeFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:string,arg15:string,arg16:number):Promise<string>;
